message:
  invalid-booster-type: [
      "[&c&l| &cInvalid Booster!](hover: &fAvailable Types: &r\n%boosters_booster-types_&b&l\\| &7{type}&f, \n%)"
  ]
  un-applicable-booster-type: [
      "[&c&l| &cUn-Applicable Booster!](hover: &fA booster of this type is already active!)"
  ]
  activated-booster: [
      "[&a&l| &aActivated Booster!](hover: &fSuccessfully activated a &b{formatted-type} &fBooster\n&fwith the duration of &b{duration}&f,\n&fmagnitude of &b{magnitude}x&f, and a &b{scope} &fscope.)"
  ]
  received-booster-voucher: [
      "[&e&l| &eReceived Booster Voucher!](hover: &fYou have been given a &b{formatted-type} &fBooster Voucher.)"
  ]
  active-boosters: [
      "[&b&l| &bActive Boosters](hover: &fClick to view all active boosters)"
  ]
  booster-expired: [
      "[&c&l| &cBooster Expired!](hover: &b{formatted-type} &fBooster expired.)"
  ]
  cancelled-booster: [
      "[&c&l| &cCancelled Booster!](hover: &b{formatted-type} &fBooster has been cancelled!)"
  ]
  reloaded-plugin: [
      "[&aSuccessfully reloaded the plugin configuration](hover: &7Took &a{time}ms.)"
  ]

booster-message:
  shop-sell-message: [
      "[&a&l| &aSell Booster Bonus! &7(+${amount})](hover: &b&l\\| &fOwner: &b{owner}\n&b&l\\| &fDuration: &b{duration}\n&b&l\\| &fMagnitude: &b{magnitude}x)"
  ]
  shop-buy-message: [
      "[&a&l| &aDiscount Booster Bonus! &7(+${amount})](hover: &b&l\\| &fOwner: &b{owner}\n&b&l\\| &fDuration: &b{duration}\n&b&l\\| &fMagnitude: &b{magnitude}x)"
  ]
  mcmmo-experience-gain-message: [
      "[&a&l| &aMcMMO Gain Booster Bonus! &7(+{amount} XP)](hover: &b&l\\| &fOwner: &b{owner}\n&b&l\\| &fDuration: &b{duration}\n&b&l\\| &fMagnitude: &b{magnitude}x)"
  ]
  experience-gain-message: [
      "[&a&l| &aExperience Gain Booster Bonus! &7(+{amount} XP)](hover: &b&l\\| &fOwner: &b{owner}\n&b&l\\| &fDuration: &b{duration}\n&b&l\\| &fMagnitude: &b{magnitude}x)"
  ]

booster-descriptions:
  SHOP_GUI_PLUS_SELL: "&fa shop oriented booster which multiplies;&fshop sells by the given booster magnitude"
  SHOP_GUI_PLUS_DISCOUNT: "&fa shop oriented booster which refunds shop;&fpurchases by the given booster magnitude"
  CROP_GROWTH: "&fa crop growth oriented booster;&fwhich speeds up crop growth times"
  MOB_DROPS: "&fa drops oriented booster which;&fincreases drops gained by killed mobs"
  MCMMO_GAIN: "&fa mcmmo oriented booster which;&fincreases mcmmo experience gained"
  EXPERIENCE_GAIN: "&fa vanilla oriented booster which;&fincreases experience gained"

enabled-types:
  SHOP_GUI_PLUS_SELL: # Discount combined with this one
  #CROP_GROWTH:
  MOB_DROPS:
  MCMMO_GAIN:
  EXPERIENCE_GAIN:
  #BLOCK_BREAK:

booster-voucher-preset:
  common:
    material: NAME_TAG
    display: "{formatted-type} Booster"
    lore:
      - " &7&l| &fMagnitude: &b{magnitude}x"
      - " &7&l| &fDuration: &b{duration}"
      - " &7&l| &fScope: &b{scope}"
      - ""
      - "&f%boosters_booster-description;{type}; &7&l| %"
      - ""
      - "&7&oClick to redeem this booster"
  rare:
    material: NAME_TAG
    display: "{formatted-type} Booster"
    lore:
      - " &7&l| &fMagnitude: &b{magnitude}x"
      - " &7&l| &fDuration: &b{duration}"
      - " &7&l| &fScope: &b{scope}"
      - ""
      - "&f%boosters_booster-description;{type}; &7&l| %"
      - ""
      - "&7&oClick to redeem this booster"
    enchantments:
      DURABILITY: 0
    flags:
      - "HIDE_ENCHANTMENTS"