name: SGBoosters
version: @version@
main: com.splicegames.sgboosters.BoostersPlugin
api-version: 1.16
author: Frcsty
softdepend: ["PlaceholderAPI", "GriefPrevention", "ShopGUIPlus", "Vault", "mcMMO"]
